# serverless.yml

org: wbeckelman
app: web
component: website
name: 8499NNationalDr
stage: dev

inputs:
  stage: ${opt:stage,self.stage}
  name: ${name}-${stage}
  src:
    src: ./src
    hook: npm run generate
    dist: ./generated
  domain: ${env:DOMAIN}
